# Generated by Django 5.2.1 on 2025-06-03 15:31

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='business_logos/%Y/%m/%d/'),
        ),
    ]
