# Generated by Django 5.2 on 2025-05-17 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencesubmission',
            name='assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_submissions', to='users.userbusiness', verbose_name='Assessor'),
        ),
        migrations.AddIndex(
            model_name='evidencesubmission',
            index=models.Index(fields=['assessor'], name='idx_evidence_assessor'),
        ),
    ]
