# Generated by Django 5.2 on 2025-05-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0003_evidencesubmission_assessor_and_more'),
        ('users', '0002_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qual',
            name='qualification_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='qual',
            unique_together={('qualification_number', 'business')},
        ),
    ]
