# Generated by Django 5.2.1 on 2025-05-30 00:20

import qualifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0004_alter_qual_qualification_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequirement',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to='media/document_templates/%Y/%m/%d/', validators=[qualifications.models.validate_file]),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='evidence_file',
            field=models.FileField(upload_to='media/evidence/%Y/%m/%d/', validators=[qualifications.models.validate_file]),
        ),
        migrations.AlterField(
            model_name='learnerdocsbyassessor',
            name='file',
            field=models.FileField(upload_to='media/learner_docs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='learnerdocumentsubmission',
            name='document_file',
            field=models.FileField(upload_to='media/learner_documents/%Y/%m/%d/', validators=[qualifications.models.validate_file]),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/message_attachments/%Y/%m/%d/', validators=[qualifications.models.validate_file]),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=models.FileField(upload_to='media/resources/%Y/%m/%d/', validators=[qualifications.models.validate_file]),
        ),
    ]
