# Generated by Django 5.2.1 on 2025-05-30 02:03

import qualifications.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0005_alter_documentrequirement_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequirement',
            name='template',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='document_templates/%Y/%m/%d/', validators=[qualifications.models.validate_file]),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='evidence_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='evidence/%Y/%m/%d/', validators=[qualifications.models.validate_file]),
        ),
        migrations.AlterField(
            model_name='learnerdocsbyassessor',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='learner_docs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='learnerdocumentsubmission',
            name='document_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='learner_documents/%Y/%m/%d/', validators=[qualifications.models.validate_file]),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='message_attachments/%Y/%m/%d/', validators=[qualifications.models.validate_file]),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='resources/%Y/%m/%d/', validators=[qualifications.models.validate_file]),
        ),
    ]
