# Generated by Django 5.2.1 on 2025-06-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0007_learner_country_learner_date_of_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
