# Generated by Django 5.2.1 on 2025-06-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0008_ac_order_lo_order_unit_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac',
            name='order',
        ),
        migrations.RemoveField(
            model_name='lo',
            name='order',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='order',
        ),
        migrations.AddField(
            model_name='ac',
            name='serial_number',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lo',
            name='serial_number',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='serial_number',
            field=models.FloatField(default=0),
        ),
    ]
