# Generated by Django 5.2.1 on 2025-06-02 06:19

import django.db.models.deletion
import qualifications.models
import storages.backends.s3
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0009_remove_ac_order_remove_lo_order_remove_unit_order_and_more'),
        ('users', '0002_business_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkbookSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workbook_file', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='workbooks/%Y/%m/%d/', validators=[qualifications.models.validate_file])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_workbooks', to='users.userbusiness', verbose_name='Assessor')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workbook_submissions', to='qualifications.lo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workbook_submissions', to='users.userbusiness')),
            ],
            options={
                'verbose_name': 'Workbook Submission',
                'verbose_name_plural': 'Workbook Submissions',
                'indexes': [models.Index(fields=['user'], name='idx_workbook_user'), models.Index(fields=['learning_outcome'], name='idx_workbook_lo'), models.Index(fields=['assessor'], name='idx_workbook_assessor')],
            },
        ),
    ]
